---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    name: voting_app
    author: intelliqit
spec:
  replicas: 2
  selector:
    matchLabels: 
      name: voting_app
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting_app
    spec:
      containers:
       - name: voting-app
         image: docker samples/examplevoting app-vote
...          
